In [31]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
import warnings
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler
warnings.filterwarnings("ignore")

In [18]:
hrdata=pd.read_csv('https://raw.githubusercontent.com/tkseneee/Dataset/dd7313e0c6487acd9ed7cd32b786782c7a1d3885/HR_data.csv')
hrdata.head(2)

,Age,Workclass,fnlwgt,Education,Education_Num,Martial_Status,Occupation,Relationship,Race,Gender,Capital_Gain,Capital_Loss,Hours_per_week,Country,Target
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K

In [19]:
#1
hrdata.isnull().sum()

Age                  0
Workclass         2079
fnlwgt               0
Education            0
Education_Num        0
Martial_Status       0
Occupation        2087
Relationship         0
Race                 0
Gender               0
Capital_Gain         0
Capital_Loss         0
Hours_per_week       0
Country            656
Target               0
dtype: int64

In [20]:
#2
num_data=hrdata.select_dtypes(include=np.number)
# num_data.isnull().sum()
print(num_data.head(2))

   Age  fnlwgt  Education_Num  Capital_Gain  Capital_Loss  Hours_per_week
0   39   77516             13          2174             0              40
1   50   83311             13             0             0              13

In [21]:
#3
num_data.max()-num_data.min()

Age                    73
fnlwgt            1472420
Education_Num          15
Capital_Gain        99999
Capital_Loss         4356
Hours_per_week         98
dtype: int64

In [25]:
#4
capital_gain_col= num_data['Capital_Gain']
std_col=capital_gain_col.std()
mean_col=capital_gain_col.mean()
scaled=(capital_gain_col-mean_col)/std_col
print(scaled.head())

0    0.149029
1   -0.146175
2   -0.146175
3   -0.146175
4   -0.146175
Name: Capital_Gain, dtype: float64

In [28]:
#5
min_val=scaled.min()
max_val=scaled.max()
mean_val=scaled.mean()
std_val=scaled.std()

print("minimum value:-",min_val,"maximum value:-",max_val,"mean value:-",mean_val,"standard deviation:-",std_val)

minimum value:- -0.14617527774434663 maximum value:- 13.432521690368429 mean value:- 2.382935503343069e-17 standard deviation:- 1.0

In [32]:
#6
scaler= StandardScaler()
scaled_data=scaler.fit_transform(num_data)
scaled_data=pd.DataFrame(scaled_data,columns=num_data.columns)
print(scaled_data.head())

        Age    fnlwgt  Education_Num  Capital_Gain  Capital_Loss  \
0  0.029050 -1.062152       1.134136      0.149031     -0.216957
1  0.834363 -1.007377       1.134136     -0.146177     -0.216957
2 -0.044160  0.243483      -0.420668     -0.146177     -0.216957
3  1.053994  0.423784      -1.198070     -0.146177     -0.216957
4 -0.776263  1.403866       1.134136     -0.146177     -0.216957

   Hours_per_week
0       -0.034641
1       -2.218354
2       -0.034641
3       -0.034641
4       -0.034641

In [33]:
#7
scaled_data_mean=scaled_data.mean()
scaled_data_std=scaled_data.std()
print(scaled_data_mean)
print(scaled_data_std)

Age               4.551893e-17
fnlwgt            1.279977e-16
Education_Num    -2.373209e-17
Capital_Gain     -6.370705e-17
Capital_Loss     -6.234537e-17
Hours_per_week    8.996797e-17
dtype: float64
Age               1.000014
fnlwgt            1.000014
Education_Num     1.000014
Capital_Gain      1.000014
Capital_Loss      1.000014
Hours_per_week    1.000014
dtype: float64

In [34]:
#8
inverse_data=scaler.inverse_transform(scaled_data)
inverse_data=pd.DataFrame(inverse_data,columns=num_data.columns)
print(inverse_data.head())

    Age    fnlwgt  Education_Num  Capital_Gain  Capital_Loss  Hours_per_week
0  39.0   77516.0           13.0        2174.0           0.0            40.0
1  50.0   83311.0           13.0           0.0           0.0            13.0
2  38.0  215646.0            9.0           0.0           0.0            40.0
3  53.0  234721.0            7.0           0.0           0.0            40.0
4  28.0  338409.0           13.0           0.0           0.0            40.0

In [37]:
#9
min_max_scaler=MinMaxScaler()
scaled_data_mm=min_max_scaler.fit_transform(num_data)
scaled_data_mm=pd.DataFrame(scaled_data_mm,columns=num_data.columns)
(max_val_mm,min_val_mm)=(scaled_data_mm.max(),scaled_data_mm.min())
(max_val_mm,min_val_mm)

(Age               1.0
 fnlwgt            1.0
 Education_Num     1.0
 Capital_Gain      1.0
 Capital_Loss      1.0
 Hours_per_week    1.0
 dtype: float64,
 Age               0.0
 fnlwgt            0.0
 Education_Num     0.0
 Capital_Gain      0.0
 Capital_Loss      0.0
 Hours_per_week    0.0
 dtype: float64)

In [38]:
#10
robust_scaler=RobustScaler()
scaled_data_rb=robust_scaler.fit_transform(num_data)
scaled_data_rb=pd.DataFrame(scaled_data_rb,columns=num_data.columns)
# (max_val_rb,min_val_rb)=(scaled_data_rb.max(),scaled_data_rb.min())
scaled_data_rb.head()

    Age    fnlwgt  Education_Num  Capital_Gain  Capital_Loss  Hours_per_week
0  0.10 -0.841482       1.000000        2174.0           0.0             0.0
1  0.65 -0.793073       1.000000           0.0           0.0            -5.4
2  0.05  0.312399      -0.333333           0.0           0.0             0.0
3  0.80  0.471744      -1.000000           0.0           0.0             0.0
4 -0.45  1.337911       1.000000           0.0           0.0             0.0